//! retained 求值语义的运行时（001 §2：入边无脏 → 不重求值）。
//!
//! 命中条件（同时满足才允许记录/命中）：
//! - 组件经 `#[derive(DslComponent)]` 声明（State = ()，无"私有状态变化绕过边"的
//!   陈旧风险）；
//! - child 内容已物化为无动作的 retained 槽位快照（不会跨帧保存调用栈 closure）；
//! - render 输出只携带 watch 计划（无 ActionTarget / 组件动作 / 动画调度请求）；
//! - 宿主经 `begin_build_for_frame` 声明本帧 dirty 集（signal 驱动帧），且缓存子树
//!   内任何订阅的解析 key 都不在 dirty 集；
//! - 上次实例快照的身份比较通过（宏生成的纯 `SignalId` u64 比较，零内容比较）。
//!
//! 候选-提交-丢弃三段与 owner 运行时同构：失败候选不污染 active 缓存；提交按本帧
//! `seen` 回收不再存在的条目。所有主键都是整数 [`ScopeId`]——热路径无字符串比较。

use std::{
    any::Any,
    cell::RefCell,
    collections::{BTreeMap, BTreeSet},
    rc::Rc,
};

use tela_contract::{SemanticKey, UiNode};
use tela_core::UiTree;

use crate::owner::{ComponentIdentity, ScopeId};
use crate::view::{PendingWatch, ViewBuild, ViewOutput, ViewResult, ViewSite};

/// Type-erased, monomorphized retained evaluator generated for each derive component.
///
/// The cached input is deliberately passed as an `Rc`: re-entry consumes only its identity and
/// never reconstructs props through a parent render stack.
pub(crate) type MemoRender<A> =
    fn(&mut ViewBuild<A>, Rc<dyn Any>, ViewSite) -> ViewResult<ViewOutput<A>>;

/// One active retained root selected for a candidate re-entry.
pub(crate) type RetainedEntry<A> = (ScopeId, SemanticKey, Rc<MemoEntry<A>>);

/// 一条 render 记忆条目：上次实例快照 + 输出快照 + 子树身份清单。
///
/// 快照即自包含的 retained element（001 §7 P3 地基）：全 watch 字段的组件实例
/// 可在不经过父级的情况下独立重入。
pub(crate) struct MemoEntry<A> {
    /// 类型擦除的上次组件实例快照（字段全为 Signal/Computed 句柄，clone = Rc 递增）。
    pub(crate) inputs: Rc<dyn Any>,
    /// Stable component identity required to re-enter this element without walking its parent.
    pub(crate) identity: ComponentIdentity,
    /// Original call site, retained for scoped provide diagnostics during re-entry.
    pub(crate) site: ViewSite,
    /// Component-specific evaluator generated by `#[derive(DslComponent)]`.
    pub(crate) rerender: MemoRender<A>,
    /// 缓存的 render 输出根。命中时把同一个 Rc 直接 splice 回新树，而非克隆节点。
    pub(crate) node: Rc<UiNode>,
    /// 缓存输出携带的全部 watch（含嵌套子树，锚点已 rebase 到缓存节点内的最终位置）；
    /// 命中时原样重新声明，`ComponentRuntime::reconcile` 按 `(key, signal_id)` 复用订阅。
    pub(crate) watches: Vec<PendingWatch>,
    /// 本子树内所有组件身份（含自身），供 owner frame 补登记 `seen`，
    /// 防止跳过子树被误判 Unmounted / 丢 State。
    pub(crate) subtree: BTreeSet<ComponentIdentity>,
}

/// 候选帧的共享记忆容器；构建期间由 `ViewBuild` 写入，提交时整体替换 active。
pub(crate) struct MemoCandidate<A> {
    pub(crate) entries: BTreeMap<ScopeId, Rc<MemoEntry<A>>>,
    pub(crate) seen: BTreeSet<ScopeId>,
    /// Retained scope -> root coordinate in this candidate tree. Coordinates belong to the
    /// candidate, so a rejected frame must not mutate the active mapping.
    pub(crate) root_keys: BTreeMap<ScopeId, SemanticKey>,
}

impl<A> Clone for MemoCandidate<A> {
    fn clone(&self) -> Self {
        Self {
            entries: self.entries.clone(),
            seen: self.seen.clone(),
            root_keys: self.root_keys.clone(),
        }
    }
}

impl<A> Default for MemoCandidate<A> {
    fn default() -> Self {
        Self {
            entries: BTreeMap::new(),
            seen: BTreeSet::new(),
            root_keys: BTreeMap::new(),
        }
    }
}

/// 每个组件 scope 在上一次成功提交中订阅的解析 key 集合。
/// `Rc` 共享快照：每帧只克隆句柄，不深拷整表。
pub(crate) type WatchKeysByScope = BTreeMap<ScopeId, BTreeSet<SemanticKey>>;

/// retained 运行时。与动作类型无关，可挂在任意 `FrameCoordinator` 上。
pub(crate) struct RenderMemoRuntime<A> {
    active: BTreeMap<ScopeId, Rc<MemoEntry<A>>>,
    root_keys: BTreeMap<ScopeId, SemanticKey>,
    /// Graph dirty key -> every retained root whose cached subtree contains that watch.
    /// Built on commit, so frame-time tree scheduling never scans all retained entries.
    dirty_entries_by_key: BTreeMap<SemanticKey, BTreeSet<ScopeId>>,
    pending: Option<Rc<RefCell<MemoCandidate<A>>>>,
    watch_keys: Rc<WatchKeysByScope>,
}

impl<A> Default for RenderMemoRuntime<A> {
    fn default() -> Self {
        Self {
            active: BTreeMap::new(),
            root_keys: BTreeMap::new(),
            dirty_entries_by_key: BTreeMap::new(),
            pending: None,
            watch_keys: Rc::new(BTreeMap::new()),
        }
    }
}

impl<A> RenderMemoRuntime<A> {
    pub(crate) fn new() -> Self {
        Self::default()
    }

    /// 开始一个候选帧：条目表从待提交候选或 active 浅复制（条目本身经 `Rc` 共享），
    /// 返回共享容器与 watch-key 快照（`Rc`，无整表深拷）。
    pub(crate) fn begin_frame(&mut self) -> (Rc<RefCell<MemoCandidate<A>>>, Rc<WatchKeysByScope>) {
        let entries = self
            .pending
            .as_ref()
            .map(|pending| pending.borrow().entries.clone())
            .unwrap_or_else(|| self.active.clone());
        let root_keys = self
            .pending
            .as_ref()
            .map(|pending| pending.borrow().root_keys.clone())
            .unwrap_or_else(|| self.root_keys.clone());
        let candidate = Rc::new(RefCell::new(MemoCandidate {
            entries,
            seen: BTreeSet::new(),
            root_keys,
        }));
        self.pending = Some(Rc::clone(&candidate));
        (candidate, Rc::clone(&self.watch_keys))
    }

    /// 原子提交候选记忆，并刷新"scope → 订阅 key"映射。
    pub(crate) fn commit(
        &mut self,
        candidate: Rc<RefCell<MemoCandidate<A>>>,
        watch_scopes: Vec<(ScopeId, SemanticKey)>,
    ) {
        let MemoCandidate {
            entries,
            seen,
            root_keys,
        } = candidate.borrow().clone();
        let mut active = BTreeMap::new();
        for (scope, entry) in entries {
            if seen.contains(&scope) {
                active.insert(scope, entry);
            }
        }
        let mut watch_keys = WatchKeysByScope::new();
        for (scope, key) in watch_scopes {
            watch_keys.entry(scope).or_default().insert(key);
        }
        self.active = active;
        self.root_keys = root_keys
            .into_iter()
            .filter(|(scope, _)| self.active.contains_key(scope))
            .collect();
        self.watch_keys = Rc::new(watch_keys);
        self.rebuild_dirty_entry_index();
        self.pending = None;
    }

    /// 只刷新"scope → 订阅 key"映射（retained 未启用的帧也必须调用，
    /// 否则组件移动后旧映射会让后续帧误命中）。
    pub(crate) fn refresh_watch_keys(&mut self, watch_scopes: Vec<(ScopeId, SemanticKey)>) {
        let mut watch_keys = WatchKeysByScope::new();
        for (scope, key) in watch_scopes {
            watch_keys.entry(scope).or_default().insert(key);
        }
        self.watch_keys = Rc::new(watch_keys);
        self.rebuild_dirty_entry_index();
    }

    /// 丢弃未随成功帧提交的候选记忆（`Rc` 丢弃即可；active 不受影响）。
    pub(crate) fn discard_pending(&mut self) {
        self.pending = None;
    }

    fn rebuild_dirty_entry_index(&mut self) {
        let mut index = BTreeMap::<SemanticKey, BTreeSet<ScopeId>>::new();
        for (retained_scope, entry) in &self.active {
            for identity in &entry.subtree {
                let Some(keys) = self.watch_keys.get(&identity.scope()) else {
                    continue;
                };
                for key in keys {
                    index
                        .entry(key.clone())
                        .or_default()
                        .insert(*retained_scope);
                }
            }
        }
        self.dirty_entries_by_key = index;
    }

    /// Records each retained entry's actual root coordinate after the candidate tree has been
    /// formed. Entries that were not spliced into this candidate are deliberately omitted and
    /// will be reclaimed on commit with the rest of the unseen candidate state.
    pub(crate) fn bind_candidate_root_keys(
        &self,
        candidate: &Rc<RefCell<MemoCandidate<A>>>,
        tree: &UiTree,
    ) {
        let keys = tree.shared_key_index();
        let roots = candidate
            .borrow()
            .entries
            .iter()
            .filter_map(|(scope, entry)| {
                keys.get(&(Rc::as_ptr(&entry.node) as usize))
                    .cloned()
                    .map(|key| (*scope, key))
            })
            .collect();
        candidate.borrow_mut().root_keys = roots;
    }

    /// Records retained roots from resolved watch coordinates. This is necessary for a retained
    /// component used as a `<For>` item: collection identity decoration path-copies the item
    /// root after the component records its cache entry, so the cached pre-decoration `Rc` is no
    /// longer present in the final tree. A derive component's own watch is always anchored at
    /// its output root, making the resolved scope/key pair the authoritative coordinate.
    pub(crate) fn bind_candidate_watch_root_keys(
        &self,
        candidate: &Rc<RefCell<MemoCandidate<A>>>,
        watch_scopes: &[(ScopeId, SemanticKey)],
    ) {
        let mut candidate = candidate.borrow_mut();
        for (scope, key) in watch_scopes {
            if candidate.entries.contains_key(scope) {
                candidate.root_keys.insert(*scope, key.clone());
            }
        }
    }

    /// Returns the innermost retained roots responsible for this dirty set. A retained parent
    /// may hold materialized children slots, so a child's dirty edge must re-enter that child
    /// directly and splice it into the shared parent subtree instead of rebuilding the parent.
    /// The result is tree-coordinate based; no component input or rendered content participates
    /// in this selection.
    pub(crate) fn outermost_dirty_roots(
        &self,
        tree: &UiTree,
        dirty: &BTreeSet<SemanticKey>,
    ) -> Vec<(ScopeId, SemanticKey)> {
        let scopes = dirty
            .iter()
            .filter_map(|key| self.dirty_entries_by_key.get(key))
            .flat_map(|scopes| scopes.iter().copied())
            .collect::<BTreeSet<_>>();
        let mut candidates: Vec<(ScopeId, SemanticKey, Vec<tela_contract::NodeId>)> = scopes
            .into_iter()
            .filter_map(|scope| {
                let key = self.root_keys.get(&scope)?.clone();
                let node = tree.node_id_for_key(&key)?;
                Some((scope, key, tree.logical_path(node)?))
            })
            .collect();
        candidates.sort_by_key(|(_, _, path)| std::cmp::Reverse(path.len()));
        let mut selected = Vec::new();
        for (scope, key, path) in candidates {
            if selected.iter().any(
                |(_, _, descendant): &(ScopeId, SemanticKey, Vec<tela_contract::NodeId>)| {
                    descendant.starts_with(&path)
                },
            ) {
                continue;
            }
            selected.push((scope, key, path));
        }
        selected
            .into_iter()
            .map(|(scope, key, _)| (scope, key))
            .collect()
    }

    /// Clones the active entries selected for independent re-entry. The clone is only an `Rc`
    /// increment; snapshots and shared subtrees remain immutable.
    pub(crate) fn active_entries(
        &self,
        roots: &[(ScopeId, SemanticKey)],
    ) -> Option<Vec<RetainedEntry<A>>> {
        roots
            .iter()
            .map(|(scope, key)| {
                self.active
                    .get(scope)
                    .map(|entry| (*scope, key.clone(), Rc::clone(entry)))
            })
            .collect()
    }

    /// Marks active entries outside independently re-entered subtrees as present in this
    /// candidate. Root projection normally does this through `memo_hit`; direct scheduling must
    /// preserve the same ownership/cache lifecycle without visiting clean siblings.
    pub(crate) fn retain_active_entries_except(
        &self,
        candidate: &Rc<RefCell<MemoCandidate<A>>>,
        reentered: &BTreeSet<ComponentIdentity>,
    ) {
        let mut candidate = candidate.borrow_mut();
        for (scope, entry) in &self.active {
            if reentered.iter().any(|identity| identity.scope() == *scope) {
                continue;
            }
            candidate.seen.insert(*scope);
            candidate
                .seen
                .extend(entry.subtree.iter().map(ComponentIdentity::scope));
        }
    }
}

#[cfg(test)]
mod tests {
    use tela_contract::NodeKind;

    use super::*;

    fn unused_rerender(
        _build: &mut ViewBuild<()>,
        _inputs: Rc<dyn Any>,
        _site: ViewSite,
    ) -> ViewResult<ViewOutput<()>> {
        unreachable!("memo runtime unit entries are never re-entered")
    }

    fn entry(inputs_value: u32) -> Rc<MemoEntry<()>> {
        Rc::new(MemoEntry {
            inputs: Rc::new(inputs_value),
            identity: ComponentIdentity::from_scoped_site(
                "memo-test",
                ScopeId::ROOT,
                ViewSite::new(file!(), line!(), column!()),
                None,
            ),
            site: ViewSite::new(file!(), line!(), column!()),
            rerender: unused_rerender,
            node: Rc::new(UiNode::new(NodeKind::View)),
            watches: Vec::new(),
            subtree: BTreeSet::new(),
        })
    }

    #[test]
    fn commit_keeps_only_seen_entries_and_discard_keeps_active() {
        let mut runtime = RenderMemoRuntime::<()>::new();
        let (candidate, _) = runtime.begin_frame();
        candidate
            .borrow_mut()
            .entries
            .insert(ScopeId::ROOT, entry(1));
        candidate
            .borrow_mut()
            .entries
            .insert(ScopeId::test_id(2), entry(2));
        candidate.borrow_mut().seen.insert(ScopeId::ROOT);
        runtime.commit(candidate, Vec::new());

        // 未 seen 的条目被回收；丢弃的候选不会污染 active。
        let (candidate, _) = runtime.begin_frame();
        candidate
            .borrow_mut()
            .entries
            .insert(ScopeId::test_id(3), entry(3));
        runtime.discard_pending();
        let (candidate, _) = runtime.begin_frame();
        assert!(candidate.borrow().entries.contains_key(&ScopeId::ROOT));
        assert!(
            !candidate
                .borrow()
                .entries
                .contains_key(&ScopeId::test_id(2))
        );
        assert!(
            !candidate
                .borrow()
                .entries
                .contains_key(&ScopeId::test_id(3))
        );
    }

    #[test]
    fn commit_records_watch_scopes_for_the_dirty_check() {
        let mut runtime = RenderMemoRuntime::<()>::new();
        let (candidate, _) = runtime.begin_frame();
        runtime.commit(
            candidate,
            vec![
                (ScopeId::test_id(7), SemanticKey("/0/".to_owned())),
                (ScopeId::test_id(7), SemanticKey("/0/1".to_owned())),
            ],
        );
        let (_, keys) = runtime.begin_frame();
        assert_eq!(
            keys.get(&ScopeId::test_id(7)),
            Some(&BTreeSet::from([
                SemanticKey("/0/".to_owned()),
                SemanticKey("/0/1".to_owned())
            ]))
        );
    }
}
