//! retained 求值语义的运行时（001 §2：入边无脏 → 不重求值）。
//!
//! 命中条件（同时满足才允许记录/命中）：
//! - 组件经 `#[derive(DslComponent)]` 声明（State = ()，无"私有状态变化绕过边"的
//!   陈旧风险）；
//! - child 内容已物化为 retained 槽位快照（不会跨帧保存调用栈 closure；路由与动画以
//!   candidate-cloneable blueprint 保存）；
//! - HostInput、Parent Event 路由和按组件 scope 归属的动画调度都以不可变 blueprint / 快照
//!   随 retained entry 保存，并在候选中重新安装；
//! - 宿主经 `begin_build_for_frame` 声明本帧 dirty 集（signal 驱动帧），且缓存子树
//!   内任何订阅的解析 key 都不在 dirty 集；
//! - 上次实例快照的身份比较通过（宏生成的纯 `SignalId` u64 比较，零内容比较）。
//!
//! 候选-提交-丢弃三段与 owner 运行时同构：失败候选不污染 active 缓存；提交按本帧
//! `seen` 回收不再存在的条目。所有主键都是整数 [`ScopeId`]——热路径无字符串比较。

use std::{
    any::Any,
    cell::RefCell,
    collections::{BTreeMap, BTreeSet},
    rc::Rc,
};

use tela_contract::{SemanticKey, UiNode};
use tela_core::UiTree;

use crate::owner::{ComponentEventRoute, ComponentHostInputRoute, ComponentIdentity, ScopeId};
use crate::view::{
    AnimationSchedules, HostInputKeyOwners, PendingPresentationBinding, PendingStructuralWatch,
    PendingWatch, RetainedSlots, ViewBuild, ViewOutput, ViewResult, ViewSite,
};

/// Type-erased, monomorphized retained evaluator generated for each derive component.
///
/// The cached input is deliberately passed as an `Rc`: re-entry consumes only its identity and
/// never reconstructs props through a parent render stack.
pub(crate) type MemoRender<A> =
    fn(&mut ViewBuild<A>, Rc<dyn Any>, ViewSite) -> ViewResult<ViewOutput<A>>;

/// One active retained root selected for a candidate re-entry.
pub(crate) type RetainedEntry<A> = (ScopeId, SemanticKey, Rc<MemoEntry<A>>);

/// 一条 render 记忆条目：上次实例快照 + 输出快照 + 子树身份清单。
///
/// 快照即自包含的 retained element（001 §7 P3 地基）：全 watch 字段的组件实例
/// 可在不经过父级的情况下独立重入。
pub(crate) struct MemoEntry<A> {
    /// 类型擦除的上次组件实例快照（字段全为 Signal/Computed 句柄，clone = Rc 递增）。
    pub(crate) inputs: Rc<dyn Any>,
    /// Candidate-owned materialized children slots. Keeping these outside the type-erased
    /// component snapshot lets a deepest-first re-entry replace a child slot without cloning or
    /// mutating the parent component instance that owns the snapshot.
    pub(crate) children: RetainedSlots<A>,
    /// Stable component identity required to re-enter this element without walking its parent.
    pub(crate) identity: ComponentIdentity,
    /// Original call site, retained for scoped provide diagnostics during re-entry.
    pub(crate) site: ViewSite,
    /// Component-specific evaluator generated by `#[derive(DslComponent)]`.
    pub(crate) rerender: MemoRender<A>,
    /// 缓存的 render 输出根。命中时把同一个 Rc 直接 splice 回新树，而非克隆节点。
    pub(crate) node: Rc<UiNode>,
    /// 缓存输出携带的全部 watch（含嵌套子树，锚点已 rebase 到缓存节点内的最终位置）；
    /// 命中时原样重新声明，`ComponentRuntime::reconcile` 按 `(key, signal_id)` 复用订阅。
    pub(crate) watches: Vec<PendingWatch>,
    /// Transparent built-ins may own an explicit source edge without owning a physical node.
    /// The lease target travels with the same retained snapshot so re-entry neither borrows a
    /// descendant key nor loses the edge for an empty structure.
    pub(crate) structural_watches: Vec<PendingStructuralWatch>,
    /// Cached static presentation bindings travel with the same immutable output root. A memo
    /// hit must re-register them so structural reconciliation neither leaks an unmounted binding
    /// nor silently drops a retained one.
    pub(crate) presentation_bindings: Vec<PendingPresentationBinding>,
    /// HostInput route blueprints declared by this retained output. They are copied into every
    /// candidate that reuses or independently rebuilds this entry; active routes remain live
    /// until that candidate is presented.
    pub(crate) host_input_routes: Vec<Box<dyn ComponentHostInputRoute<A>>>,
    /// Private provenance for the route targets above. Retained reuse carries this proof with
    /// the immutable route blueprints, so a wrapper cannot claim a descendant it did not create.
    pub(crate) host_input_key_owners: HostInputKeyOwners,
    /// Nested child-to-parent Event handlers declared while this entry was first assembled.
    /// The outer component's own handler is registered after `UiSpec::assemble` returns and is
    /// therefore intentionally not stored here.
    pub(crate) component_events: BTreeMap<ComponentIdentity, Box<dyn ComponentEventRoute<A>>>,
    /// Active animation requests owned by component scopes in this retained subtree. A re-entry
    /// replaces these scopes instead of preserving an old active request.
    pub(crate) animation_schedules: AnimationSchedules,
    /// 本子树内所有组件身份（含自身），供 owner frame 补登记 `seen`，
    /// 防止跳过子树被误判 Unmounted / 丢 State。
    pub(crate) subtree: BTreeSet<ComponentIdentity>,
}

/// 候选帧的共享记忆容器；构建期间由 `ViewBuild` 写入，提交时整体替换 active。
pub(crate) struct MemoCandidate<A> {
    pub(crate) entries: BTreeMap<ScopeId, Rc<MemoEntry<A>>>,
    pub(crate) seen: BTreeSet<ScopeId>,
    /// Retained scope -> root coordinate in this candidate tree. Coordinates belong to the
    /// candidate, so a rejected frame must not mutate the active mapping.
    pub(crate) root_keys: BTreeMap<ScopeId, SemanticKey>,
}

impl<A> Clone for MemoCandidate<A> {
    fn clone(&self) -> Self {
        Self {
            entries: self.entries.clone(),
            seen: self.seen.clone(),
            root_keys: self.root_keys.clone(),
        }
    }
}

impl<A> Default for MemoCandidate<A> {
    fn default() -> Self {
        Self {
            entries: BTreeMap::new(),
            seen: BTreeSet::new(),
            root_keys: BTreeMap::new(),
        }
    }
}

/// 每个组件 scope 在上一次成功提交中订阅的解析 key 集合。
/// `Rc` 共享快照：每帧只克隆句柄，不深拷整表。
pub(crate) type WatchKeysByScope = BTreeMap<ScopeId, BTreeSet<SemanticKey>>;

/// 已解析的树坐标反查到直接声明它的组件 scope。
///
/// 这个索引和 retained 子树索引刻意不是一回事：一个父 retained 条目会覆盖子树的
/// 所有 watch，但只有直接 owning scope 才能说明哪一个 view 必须重新执行。把二者混为
/// 一谈会在父子同时变脏时错误地只重入最深子树，丢掉父自己的变化。
type WatchScopesByKey = BTreeMap<SemanticKey, BTreeSet<ScopeId>>;

/// retained 运行时。与动作类型无关，可挂在任意 `FrameCoordinator` 上。
pub(crate) struct RenderMemoRuntime<A> {
    active: BTreeMap<ScopeId, Rc<MemoEntry<A>>>,
    root_keys: BTreeMap<ScopeId, SemanticKey>,
    /// Graph dirty key -> the scopes that directly declared that watch. Built on commit, so
    /// frame-time retained scheduling never scans all active component entries.
    watch_scopes_by_key: WatchScopesByKey,
    pending: Option<Rc<RefCell<MemoCandidate<A>>>>,
    watch_keys: Rc<WatchKeysByScope>,
}

impl<A> Default for RenderMemoRuntime<A> {
    fn default() -> Self {
        Self {
            active: BTreeMap::new(),
            root_keys: BTreeMap::new(),
            watch_scopes_by_key: BTreeMap::new(),
            pending: None,
            watch_keys: Rc::new(BTreeMap::new()),
        }
    }
}

impl<A> RenderMemoRuntime<A> {
    pub(crate) fn new() -> Self {
        Self::default()
    }

    /// 开始一个候选帧：条目表从待提交候选或 active 浅复制（条目本身经 `Rc` 共享），
    /// 返回共享容器与 watch-key 快照（`Rc`，无整表深拷）。
    pub(crate) fn begin_frame(&mut self) -> (Rc<RefCell<MemoCandidate<A>>>, Rc<WatchKeysByScope>) {
        let entries = self
            .pending
            .as_ref()
            .map(|pending| pending.borrow().entries.clone())
            .unwrap_or_else(|| self.active.clone());
        let root_keys = self
            .pending
            .as_ref()
            .map(|pending| pending.borrow().root_keys.clone())
            .unwrap_or_else(|| self.root_keys.clone());
        let candidate = Rc::new(RefCell::new(MemoCandidate {
            entries,
            seen: BTreeSet::new(),
            root_keys,
        }));
        self.pending = Some(Rc::clone(&candidate));
        (candidate, Rc::clone(&self.watch_keys))
    }

    /// 原子提交候选记忆，并刷新"scope → 订阅 key"映射。
    pub(crate) fn commit(
        &mut self,
        candidate: Rc<RefCell<MemoCandidate<A>>>,
        watch_scopes: Vec<(ScopeId, SemanticKey)>,
    ) {
        let MemoCandidate {
            entries,
            seen,
            root_keys,
        } = candidate.borrow().clone();
        let mut active = BTreeMap::new();
        for (scope, entry) in entries {
            if seen.contains(&scope) {
                active.insert(scope, entry);
            }
        }
        let mut watch_keys = WatchKeysByScope::new();
        for (scope, key) in watch_scopes {
            watch_keys.entry(scope).or_default().insert(key);
        }
        self.active = active;
        self.root_keys = root_keys
            .into_iter()
            .filter(|(scope, _)| self.active.contains_key(scope))
            .collect();
        self.watch_keys = Rc::new(watch_keys);
        self.rebuild_watch_scope_index();
        self.pending = None;
    }

    /// 只刷新"scope → 订阅 key"映射（retained 未启用的帧也必须调用，
    /// 否则组件移动后旧映射会让后续帧误命中）。
    pub(crate) fn refresh_watch_keys(&mut self, watch_scopes: Vec<(ScopeId, SemanticKey)>) {
        let mut watch_keys = WatchKeysByScope::new();
        for (scope, key) in watch_scopes {
            watch_keys.entry(scope).or_default().insert(key);
        }
        self.watch_keys = Rc::new(watch_keys);
        self.rebuild_watch_scope_index();
    }

    /// 丢弃未随成功帧提交的候选记忆（`Rc` 丢弃即可；active 不受影响）。
    pub(crate) fn discard_pending(&mut self) {
        self.pending = None;
    }

    fn rebuild_watch_scope_index(&mut self) {
        let mut index = WatchScopesByKey::new();
        for (scope, keys) in self.watch_keys.iter() {
            for key in keys {
                index.entry(key.clone()).or_default().insert(*scope);
            }
        }
        self.watch_scopes_by_key = index;
    }

    /// Records each retained entry's actual root coordinate after the candidate tree has been
    /// formed. Entries that were not spliced into this candidate are deliberately omitted and
    /// will be reclaimed on commit with the rest of the unseen candidate state.
    pub(crate) fn bind_candidate_root_keys(
        &self,
        candidate: &Rc<RefCell<MemoCandidate<A>>>,
        tree: &UiTree,
    ) {
        let keys = tree.shared_key_index();
        let roots = candidate
            .borrow()
            .entries
            .iter()
            .filter_map(|(scope, entry)| {
                keys.get(&(Rc::as_ptr(&entry.node) as usize))
                    .cloned()
                    .map(|key| (*scope, key))
            })
            .collect();
        candidate.borrow_mut().root_keys = roots;
    }

    /// Records retained roots from resolved watch coordinates. This is necessary for a retained
    /// component used as a `<For>` item: collection identity decoration path-copies the item
    /// root after the component records its cache entry, so the cached pre-decoration `Rc` is no
    /// longer present in the final tree. A derive component's own watch is always anchored at
    /// its output root, making the resolved scope/key pair the authoritative coordinate.
    pub(crate) fn bind_candidate_watch_root_keys(
        &self,
        candidate: &Rc<RefCell<MemoCandidate<A>>>,
        watch_scopes: &[(ScopeId, SemanticKey)],
    ) {
        let mut candidate = candidate.borrow_mut();
        for (scope, key) in watch_scopes {
            if candidate.entries.contains_key(scope) {
                candidate.root_keys.insert(*scope, key.clone());
            }
        }
    }

    /// Returns retained roots eligible for one candidate re-entry pass.
    ///
    /// A selected root must directly own every dirty watch assigned to it. Roots may nest: the
    /// frame coordinator evaluates the deepest entry first and passes its candidate child slot
    /// into each ancestor before selecting only outermost node replacements for the final tree
    /// splice. Ordinary components without their own retained entry still force rooted assembly.
    ///
    /// `None` means that this dirty set is not safe for independent re-entry. The result remains
    /// tree-coordinate based; no component input or rendered content participates in selection.
    pub(crate) fn independently_reenterable_dirty_roots(
        &self,
        tree: &UiTree,
        dirty: &BTreeSet<SemanticKey>,
    ) -> Option<Vec<(ScopeId, SemanticKey)>> {
        let mut scopes = BTreeSet::new();
        for key in dirty {
            let watched_scopes = self.watch_scopes_by_key.get(key)?;
            scopes.extend(watched_scopes.iter().copied());
        }
        let mut candidates = Vec::with_capacity(scopes.len());
        for scope in scopes {
            // A watch owned by an ordinary component/root function has no retained entry of its
            // own. It cannot be skipped merely because another dirty key happens to have one.
            // Falling back here preserves the one rooted candidate as the semantic authority.
            let key = self.root_keys.get(&scope)?.clone();
            let node = tree.node_id_for_key(&key)?;
            candidates.push((scope, key, tree.logical_path(node)?));
        }
        if candidates.is_empty() {
            return None;
        }
        candidates.sort_by_key(|(_, _, path)| path.len());
        Some(
            candidates
                .into_iter()
                .map(|(scope, key, _)| (scope, key))
                .collect(),
        )
    }

    /// Clones the active entries selected for independent re-entry. The clone is only an `Rc`
    /// increment; snapshots and shared subtrees remain immutable.
    pub(crate) fn active_entries(
        &self,
        roots: &[(ScopeId, SemanticKey)],
    ) -> Option<Vec<RetainedEntry<A>>> {
        roots
            .iter()
            .map(|(scope, key)| {
                self.active
                    .get(scope)
                    .map(|entry| (*scope, key.clone(), Rc::clone(entry)))
            })
            .collect()
    }

    /// Marks active entries outside independently re-entered subtrees as present in this
    /// candidate. Root projection normally does this through `memo_hit`; direct scheduling must
    /// preserve the same ownership/cache lifecycle without visiting clean siblings.
    pub(crate) fn retain_active_entries_except(
        &self,
        candidate: &Rc<RefCell<MemoCandidate<A>>>,
        reentered: &BTreeSet<ComponentIdentity>,
    ) {
        let mut candidate = candidate.borrow_mut();
        for (scope, entry) in &self.active {
            if reentered.iter().any(|identity| identity.scope() == *scope) {
                continue;
            }
            candidate.seen.insert(*scope);
            candidate
                .seen
                .extend(entry.subtree.iter().map(ComponentIdentity::scope));
        }
    }
}

#[cfg(test)]
mod tests {
    use tela_contract::NodeKind;

    use super::*;

    fn unused_rerender(
        _build: &mut ViewBuild<()>,
        _inputs: Rc<dyn Any>,
        _site: ViewSite,
    ) -> ViewResult<ViewOutput<()>> {
        unreachable!("memo runtime unit entries are never re-entered")
    }

    fn entry(inputs_value: u32) -> Rc<MemoEntry<()>> {
        Rc::new(MemoEntry {
            inputs: Rc::new(inputs_value),
            children: RetainedSlots::empty(),
            identity: ComponentIdentity::from_scoped_site(
                "memo-test",
                ScopeId::ROOT,
                ViewSite::new(file!(), line!(), column!()),
                None,
            ),
            site: ViewSite::new(file!(), line!(), column!()),
            rerender: unused_rerender,
            node: Rc::new(UiNode::new(NodeKind::View)),
            watches: Vec::new(),
            structural_watches: Vec::new(),
            presentation_bindings: Vec::new(),
            host_input_routes: Vec::new(),
            host_input_key_owners: HostInputKeyOwners::new(),
            component_events: BTreeMap::new(),
            animation_schedules: AnimationSchedules::new(),
            subtree: BTreeSet::new(),
        })
    }

    #[test]
    fn commit_keeps_only_seen_entries_and_discard_keeps_active() {
        let mut runtime = RenderMemoRuntime::<()>::new();
        let (candidate, _) = runtime.begin_frame();
        candidate
            .borrow_mut()
            .entries
            .insert(ScopeId::ROOT, entry(1));
        candidate
            .borrow_mut()
            .entries
            .insert(ScopeId::test_id(2), entry(2));
        candidate.borrow_mut().seen.insert(ScopeId::ROOT);
        runtime.commit(candidate, Vec::new());

        // 未 seen 的条目被回收；丢弃的候选不会污染 active。
        let (candidate, _) = runtime.begin_frame();
        candidate
            .borrow_mut()
            .entries
            .insert(ScopeId::test_id(3), entry(3));
        runtime.discard_pending();
        let (candidate, _) = runtime.begin_frame();
        assert!(candidate.borrow().entries.contains_key(&ScopeId::ROOT));
        assert!(
            !candidate
                .borrow()
                .entries
                .contains_key(&ScopeId::test_id(2))
        );
        assert!(
            !candidate
                .borrow()
                .entries
                .contains_key(&ScopeId::test_id(3))
        );
    }

    #[test]
    fn commit_records_watch_scopes_for_the_dirty_check() {
        let mut runtime = RenderMemoRuntime::<()>::new();
        let (candidate, _) = runtime.begin_frame();
        runtime.commit(
            candidate,
            vec![
                (ScopeId::test_id(7), SemanticKey("/0/".to_owned())),
                (ScopeId::test_id(7), SemanticKey("/0/1".to_owned())),
            ],
        );
        let (_, keys) = runtime.begin_frame();
        assert_eq!(
            keys.get(&ScopeId::test_id(7)),
            Some(&BTreeSet::from([
                SemanticKey("/0/".to_owned()),
                SemanticKey("/0/1".to_owned())
            ]))
        );
    }
}
