//! Explicit host-to-guest input and guest-to-host status packets.

use serde::{Deserialize, Serialize};

use crate::FrameCodecError;

const EVENT_MAGIC: [u8; 4] = *b"TLEV";
const STATUS_MAGIC: [u8; 4] = *b"TLSV";
const PACKET_VERSION: u16 = 1;
const HEADER_LEN: usize = EVENT_MAGIC.len() + std::mem::size_of::<u16>();

/// One normalized event delivered by a platform SDK to the application guest.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum AppEvent {
    /// The host content area changed in logical pixels.
    Viewport {
        /// Logical content width.
        width: f32,
        /// Logical content height.
        height: f32,
    },
    /// Primary pointer press in logical coordinates.
    PointerDown {
        /// Logical horizontal coordinate.
        x: f32,
        /// Logical vertical coordinate.
        y: f32,
    },
    /// Primary pointer release in logical coordinates.
    PointerUp {
        /// Logical horizontal coordinate.
        x: f32,
        /// Logical vertical coordinate.
        y: f32,
    },
    /// Pointer movement in logical coordinates.
    PointerMove {
        /// Logical horizontal coordinate.
        x: f32,
        /// Logical vertical coordinate.
        y: f32,
    },
    /// Pointer wheel delta in logical coordinates.
    PointerScroll {
        /// Pointer logical horizontal coordinate.
        x: f32,
        /// Pointer logical vertical coordinate.
        y: f32,
        /// Horizontal scroll delta.
        delta_x: f32,
        /// Vertical scroll delta.
        delta_y: f32,
    },
    /// A normalized USB-HID physical key press. The guest resolves it with its current keymap.
    KeyDown {
        /// `tela_contract::PhysicalKey` numeric value.
        physical_key: u16,
        /// Shift/Ctrl/Alt/Meta bit mask defined by the application keymap.
        modifier_bits: u8,
        /// Whether this event was generated by key repeat.
        repeat: bool,
    },
    /// Replace the controlled value of the focused text input.
    SetInputValue(String),
    /// The platform text editor is now focused.
    InputFocus,
    /// The platform text editor lost focus.
    InputBlur,
    /// Commit the focused draft input.
    InputEnter,
    /// Cancel the focused draft input.
    InputCancel,
    /// The platform IME began composing text for the focused input.
    ///
    /// Composition is an interaction-lifetime marker. It does not commit text by itself.
    InputCompositionStart,
    /// The platform IME finished composing text for the focused input.
    ///
    /// The host sends the resulting controlled value separately, then lets the guest decide
    /// whether an explicit confirmation should commit it.
    InputCompositionEnd,
    /// Atomically replace the runtime keymap with a validated JSON snapshot.
    ///
    /// This is intentionally an ABI event rather than a browser-only escape hatch, so every
    /// host can use the same key intent and physical-key-table pipeline.
    ReplaceKeymapJson(String),
}

/// Cursor requested by the application for the current pointer location.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u8)]
pub enum CursorKind {
    /// Default arrow cursor.
    #[default]
    Default = 0,
    /// Text editing cursor.
    Text = 1,
    /// Clickable control cursor.
    Pointer = 2,
}

/// Current guest state that a platform SDK needs outside of drawing.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct AppStatus {
    /// Requested cursor shape.
    pub cursor: CursorKind,
    /// Whether a controlled text input is focused.
    pub input_focused: bool,
    /// Current controlled input value. It lets a native host feed ordinary text input without
    /// owning business state.
    pub input_value: String,
}

/// Encodes a host-to-guest event with a versioned packet header.
pub fn encode_event(event: &AppEvent) -> Result<Vec<u8>, FrameCodecError> {
    encode_packet(EVENT_MAGIC, event)
}

/// Decodes a host-to-guest event after verifying its magic and version.
pub fn decode_event(bytes: &[u8]) -> Result<AppEvent, FrameCodecError> {
    decode_packet(EVENT_MAGIC, bytes)
}

/// Encodes guest status for consumption by a platform SDK.
pub fn encode_status(status: &AppStatus) -> Result<Vec<u8>, FrameCodecError> {
    encode_packet(STATUS_MAGIC, status)
}

/// Decodes guest status after verifying its magic and version.
pub fn decode_status(bytes: &[u8]) -> Result<AppStatus, FrameCodecError> {
    decode_packet(STATUS_MAGIC, bytes)
}

fn encode_packet<T: Serialize>(magic: [u8; 4], value: &T) -> Result<Vec<u8>, FrameCodecError> {
    let payload =
        postcard::to_allocvec(value).map_err(|error| FrameCodecError::Encode(error.to_string()))?;
    let mut bytes = Vec::with_capacity(HEADER_LEN + payload.len());
    bytes.extend_from_slice(&magic);
    bytes.extend_from_slice(&PACKET_VERSION.to_le_bytes());
    bytes.extend_from_slice(&payload);
    Ok(bytes)
}

fn decode_packet<T: for<'de> Deserialize<'de>>(
    magic: [u8; 4],
    bytes: &[u8],
) -> Result<T, FrameCodecError> {
    if bytes.len() < HEADER_LEN || bytes[..magic.len()] != magic {
        return Err(FrameCodecError::InvalidMagic);
    }
    let version = u16::from_le_bytes([bytes[4], bytes[5]]);
    if version != PACKET_VERSION {
        return Err(FrameCodecError::UnsupportedVersion(version));
    }
    let (value, remaining): (T, &[u8]) = postcard::take_from_bytes(&bytes[HEADER_LEN..])
        .map_err(|error| FrameCodecError::Decode(error.to_string()))?;
    if !remaining.is_empty() {
        return Err(FrameCodecError::TrailingBytes);
    }
    Ok(value)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn event_and_status_packets_round_trip() {
        let event = AppEvent::PointerScroll {
            x: 10.0,
            y: 20.0,
            delta_x: 1.0,
            delta_y: -2.0,
        };
        assert_eq!(
            decode_event(&encode_event(&event).expect("encode")).expect("decode"),
            event
        );
        let status = AppStatus {
            cursor: CursorKind::Text,
            input_focused: true,
            input_value: "文件".to_owned(),
        };
        assert_eq!(
            decode_status(&encode_status(&status).expect("encode")).expect("decode"),
            status
        );
    }

    #[test]
    fn extended_input_events_round_trip() {
        for event in [
            AppEvent::InputCompositionStart,
            AppEvent::InputCompositionEnd,
            AppEvent::ReplaceKeymapJson(r#"{\"bindings\":[]}"#.to_owned()),
        ] {
            assert_eq!(
                decode_event(&encode_event(&event).expect("encode")).expect("decode"),
                event
            );
        }
    }
}
