//! Platform-neutral application lifecycle, input, publication, and presentation protocol.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use std::{num::NonZeroU64, rc::Rc};

use serde::{Deserialize, Serialize};
use tela_contract::{
    FrameDamage, Point, PointerButtons, PointerEvent, PointerId, PointerKind, PointerPhase,
    SemanticKey, UiFrame, WindowCommand,
};

/// 原始指针设备类型在 Application ABI 中的稳定编码。
///
/// ABI 不直接序列化 `tela-contract` 的 Rust 值，以便 Host 与 guest 仅通过稳定的
/// packet 定义通信；guest 再把它映射为 Contract 的 `PointerKind`。
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u8)]
pub enum AppPointerKind {
    /// 鼠标或触控板指针。
    Mouse = 0,
    /// 直接触摸。
    Touch = 1,
    /// 手写笔。
    Pen = 2,
}

/// 原始指针生命周期在 Application ABI 中的稳定编码。
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u8)]
pub enum AppPointerPhase {
    /// 指针按下。
    Down = 0,
    /// 指针移动。
    Move = 1,
    /// 指针释放。
    Up = 2,
    /// 指针序列被宿主或系统取消。
    Cancel = 3,
    /// 独立滚轮或触控板滚动增量。
    Scroll = 4,
}

/// Host 传给 guest 的完整原始指针帧。
///
/// Target 只能负责将平台坐标、设备类型与按钮掩码规范化为这个 packet；不能在此之前
/// 合成 Click 或 Scroll 手势。捕获、多指、嵌套滚动与手势仲裁由 guest 的 Kernel 完成。
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppPointerEvent {
    /// 同一宿主会话内稳定的原始指针 id。
    pub pointer_id: u64,
    /// 原始设备类别。
    pub kind: AppPointerKind,
    /// 当前生命周期阶段。
    pub phase: AppPointerPhase,
    /// 当前逻辑横坐标。
    pub x: f32,
    /// 当前逻辑纵坐标。
    pub y: f32,
    /// 平台规范化后的按钮位集；与 Contract `PointerButtons` 一一对应。
    pub buttons: u16,
    /// Host 单调时钟的微秒刻度。
    pub timestamp_micros: u64,
    /// 仅 `Scroll` 阶段使用的逻辑横向增量。
    pub delta_x: f32,
    /// 仅 `Scroll` 阶段使用的逻辑纵向增量。
    pub delta_y: f32,
}

impl AppPointerEvent {
    /// 构造完整的 ABI 原始指针帧。
    #[allow(clippy::too_many_arguments)]
    pub const fn new(
        pointer_id: u64,
        kind: AppPointerKind,
        phase: AppPointerPhase,
        x: f32,
        y: f32,
        buttons: u16,
        timestamp_micros: u64,
        delta_x: f32,
        delta_y: f32,
    ) -> Self {
        Self {
            pointer_id,
            kind,
            phase,
            x,
            y,
            buttons,
            timestamp_micros,
            delta_x,
            delta_y,
        }
    }
}

impl From<AppPointerEvent> for PointerEvent {
    fn from(event: AppPointerEvent) -> Self {
        PointerEvent::new(
            PointerId(event.pointer_id),
            match event.kind {
                AppPointerKind::Mouse => PointerKind::Mouse,
                AppPointerKind::Touch => PointerKind::Touch,
                AppPointerKind::Pen => PointerKind::Pen,
            },
            match event.phase {
                AppPointerPhase::Down => PointerPhase::Down,
                AppPointerPhase::Move => PointerPhase::Move,
                AppPointerPhase::Up => PointerPhase::Up,
                AppPointerPhase::Cancel => PointerPhase::Cancel,
                AppPointerPhase::Scroll => PointerPhase::Scroll,
            },
            Point {
                x: event.x,
                y: event.y,
            },
            PointerButtons(event.buttons),
            event.timestamp_micros,
            Point {
                x: event.delta_x,
                y: event.delta_y,
            },
        )
    }
}

/// A non-zero identity for one guest frame published to a platform host.
///
/// A token becomes eligible for input only after the host actually presents the corresponding
/// frame. The host returns this value in every frame-owned input packet, so the guest can reject
/// stale input before it reaches hit testing or controlled-input state.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[repr(transparent)]
pub struct AppFrameToken(NonZeroU64);

impl AppFrameToken {
    /// Creates a frame token from a guest-generated raw value.
    ///
    /// `0` deliberately has no token meaning and is never accepted as a provenance sentinel.
    #[must_use]
    pub const fn new(raw: u64) -> Option<Self> {
        match NonZeroU64::new(raw) {
            Some(raw) => Some(Self(raw)),
            None => None,
        }
    }

    /// Returns the stable raw value carried over the application ABI.
    #[must_use]
    pub const fn get(self) -> u64 {
        self.0.get()
    }
}

/// A normalized input whose routing must be evaluated against one presented guest frame.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum AppFrameInput {
    /// An unclassified raw pointer frame.
    Pointer(AppPointerEvent),
    /// A normalized USB-HID physical key press. The guest resolves it with its current keymap.
    KeyDown {
        /// `tela_contract::PhysicalKey` numeric value.
        physical_key: u16,
        /// Shift/Ctrl/Alt/Meta bit mask defined by the application keymap.
        modifier_bits: u8,
        /// Whether this event was generated by key repeat.
        repeat: bool,
    },
    /// Replace the controlled value of the focused text input.
    SetInputValue(String),
    /// The platform text editor is now focused.
    InputFocus,
    /// The platform text editor lost focus.
    InputBlur,
    /// Commit the focused draft input.
    InputEnter,
    /// Cancel the focused draft input.
    InputCancel,
    /// The platform IME began composing text for the focused input.
    ///
    /// Composition is an interaction-lifetime marker. It does not commit text by itself.
    InputCompositionStart,
    /// The platform IME finished composing text for the focused input.
    ///
    /// The host sends the resulting controlled value separately, then lets the guest decide
    /// whether an explicit confirmation should commit it.
    InputCompositionEnd,
}

/// One normalized event delivered by a platform SDK to the application guest.
///
/// System events are independent of a rendered frame. Every interaction that can be routed to a
/// node is instead carried by [`AppEvent::FrameInput`] with the token of the frame the host
/// actually presented.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum AppEvent {
    /// Host 的低频维护唤醒，用于刷新外部快照或 heartbeat。
    Wake {
        /// Host 单调时钟的毫秒刻度。
        timestamp_ms: u64,
    },
    /// Host vsync 或定时器提供的单调时钟采样。
    ///
    /// Host 只负责调度，不得执行 easing 或属性插值；相同时间戳序列必须在 guest 中产生
    /// 相同动画帧。
    Tick {
        /// Host 单调时钟的毫秒刻度。
        timestamp_ms: u64,
    },
    /// The host content area changed in logical pixels.
    Viewport {
        /// Logical content width.
        width: f32,
        /// Logical content height.
        height: f32,
    },
    /// The native window state changed independently of application rendering.
    WindowState {
        /// Whether the window is currently maximized.
        maximized: bool,
    },
    /// An input event evaluated against the identified presented frame.
    FrameInput {
        /// Token of the frame that was actually visible when the host observed this input.
        source_frame_token: AppFrameToken,
        /// Normalized interaction data.
        input: AppFrameInput,
    },
    /// Atomically replace the runtime keymap with a validated JSON snapshot.
    ///
    /// This is intentionally an ABI event rather than a browser-only escape hatch, so every
    /// host can use the same key intent and physical-key-table pipeline.
    ReplaceKeymapJson(String),
}

/// Cursor requested by the application for the current pointer location.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u8)]
pub enum CursorKind {
    /// Default arrow cursor.
    #[default]
    Default = 0,
    /// Text editing cursor.
    Text = 1,
    /// Clickable control cursor.
    Pointer = 2,
}

/// Current guest state that a platform SDK needs outside of drawing.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct AppStatus {
    /// Identity of the most recently published guest frame.
    ///
    /// Hosts may retain it as an input source only after their renderer reports a successful
    /// present. `None` is reserved for a guest that has not produced an interactive frame.
    pub frame_token: Option<AppFrameToken>,
    /// Requested cursor shape.
    pub cursor: CursorKind,
    /// Whether a controlled text input is focused.
    pub input_focused: bool,
    /// Current controlled input value. It lets a native host feed ordinary text input without
    /// owning business state.
    pub input_value: String,
    /// guest 是否仍有需要后续 Tick 推进的动画。
    pub animation_active: bool,
    /// guest 希望被再次唤醒的最早单调毫秒时刻；`None` 表示无定时工作。
    pub next_deadline_ms: Option<u64>,
}

/// Result of initialization, event dispatch, or presentation acknowledgement.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct AppDispatchOutcome {
    /// Whether the application accepted the event.
    pub handled: bool,
    /// Whether the host should request a new publication.
    pub publish_requested: bool,
}

impl AppDispatchOutcome {
    /// A successful no-op outcome.
    pub const IDLE: Self = Self {
        handled: false,
        publish_requested: false,
    };

    /// Requests publication after a handled event.
    pub const fn changed() -> Self {
        Self {
            handled: true,
            publish_requested: true,
        }
    }
}

/// A host effect staged with a publication and committed only after presentation.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum AppEffect {
    /// Execute a native window command.
    Window(WindowCommand),
}

/// Guest-local identity view of one immutable retained UI tree.
///
/// This capability never crosses the application ABI. It gives an in-process transport sender
/// enough information to decide whether a `SemanticKey` patch has an acknowledged shared-tree
/// base, without comparing node content or reconstructing a virtual tree.
pub trait RetainedTreeSnapshot {
    /// Returns the allocation identity at one stable tree coordinate, if that coordinate exists.
    fn node_identity(&self, key: &SemanticKey) -> Option<usize>;
}

/// One atomic application publication awaiting presentation.
#[derive(Clone)]
pub struct AppPublication {
    /// Candidate frame identity.
    pub token: AppFrameToken,
    /// Resolved visual frame.
    pub frame: UiFrame,
    /// Paint damage relative to the last successfully presented frame.
    ///
    /// Initial frames and host-wide invalidations contain a full-viewport rectangle. Targets
    /// without a retained backing layer may conservatively ignore this and render `frame`.
    pub damage: FrameDamage,
    /// Retained tree coordinates replaced by this candidate, outermost paths only.
    ///
    /// An empty list means this publication is a host/global invalidation and transport must use
    /// a snapshot rather than infer a structural patch from draw commands.
    pub spine: Vec<SemanticKey>,
    /// Guest-local retained tree captured with this candidate.
    ///
    /// It is intentionally absent from the binary ABI: only a local sender uses it to retain an
    /// ACK window and validate that a structural `spine` patch has a shared-tree base.
    pub retained_tree: Option<Rc<dyn RetainedTreeSnapshot>>,
    /// Native state projection associated with `frame`.
    pub status: AppStatus,
    /// Effects that become eligible only after this publication is presented.
    pub effects: Vec<AppEffect>,
}

impl std::fmt::Debug for AppPublication {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("AppPublication")
            .field("token", &self.token)
            .field("frame", &self.frame)
            .field("damage", &self.damage)
            .field("spine", &self.spine)
            .field("retained_tree", &self.retained_tree.is_some())
            .field("status", &self.status)
            .field("effects", &self.effects)
            .finish()
    }
}

impl PartialEq for AppPublication {
    fn eq(&self, other: &Self) -> bool {
        self.token == other.token
            && self.frame == other.frame
            && self.damage == other.damage
            && self.spine == other.spine
            && self.status == other.status
            && self.effects == other.effects
    }
}

/// A platform-neutral application session failure.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SessionError(String);

impl SessionError {
    /// Creates an error from a diagnostic message.
    pub fn new(message: impl Into<String>) -> Self {
        Self(message.into())
    }
}

impl std::fmt::Display for SessionError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl std::error::Error for SessionError {}

/// Application-facing protocol shared by native and WASM-backed targets.
pub trait ApplicationSession {
    /// Initializes the application and requests its initial publication.
    fn initialize(&mut self) -> Result<AppDispatchOutcome, SessionError>;

    /// Delivers one normalized event without constructing a frame.
    fn dispatch(&mut self, event: AppEvent) -> Result<AppDispatchOutcome, SessionError>;

    /// Constructs the latest requested candidate publication.
    fn publish(&mut self) -> Result<AppPublication, SessionError>;

    /// Commits a successfully presented candidate.
    fn presented(&mut self, token: AppFrameToken) -> Result<AppDispatchOutcome, SessionError>;

    /// Rejects a candidate that could not be presented.
    fn rejected(&mut self, token: AppFrameToken);

    /// Releases application-owned resources before the target closes.
    fn close(&mut self);
}
